// RFC 9421 conformance vectors for the AAuth signing implementation.
//
// The primary vector was generated by the *Python* SDK
// (python/src/lumoauth/aauth.py, AAuthClient.sign_request) with a fixed
// Ed25519 key (seed bytes 0x00..0x1f), fixed created=1750000000 and fixed
// nonce bytes 0x00..0x0f. Ed25519 is deterministic (RFC 8032), so the
// TypeScript implementation must reproduce the signature BYTE-FOR-BYTE.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createPublicKey, createPrivateKey, generateKeyPairSync } from 'node:crypto';

import {
    signRequest,
    buildSignatureBase,
    contentDigestSha256,
    signSignatureBase,
    verifySignatureBase,
    generateNonce,
    generateKeypair,
    jwkThumbprint,
    publicJwkFromPrivateKey,
} from '../dist/aauth/index.mjs';

// ─── Fixed vector (produced by the Python SDK) ────────────────────────

const PYTHON_VECTOR = {
    privateKeyPem:
        '-----BEGIN PRIVATE KEY-----\n' +
        'MC4CAQAwBQYDK2VwBCIEIAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4f\n' +
        '-----END PRIVATE KEY-----\n',
    publicX: 'A6EHv_POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg',
    url: 'https://auth.acme.test/orgs/acme-corp/api/v1/aauth/agent/token',
    body: '{"request_type": "auth", "resource_token": "RESOURCE_TOKEN_FIXED", "scope": "read write"}',
    created: 1750000000,
    nonce: 'AAECAwQFBgcICQoLDA0ODw',
    agentToken: 'AGENT_TOKEN_FIXED',
    expected: {
        contentDigest: 'sha-256=:maoKTEBGVoe/uXlHmt4EeWj7K7xo71Ag/qIPObi3vPw=:',
        signatureInput:
            'sig1=("@method" "@authority" "@path" "signature-key" "content-digest" "content-type" "authorization");created=1750000000;nonce="AAECAwQFBgcICQoLDA0ODw"',
        signature:
            'sig1=:sr5ZGEA2-LkKN4RvFrpYxhaGPB-tf1STvf1W0bl_UAFt1Rjn_wKKCouOHsFamkDAf85UpwF_HOJXLs07-bynCw:',
        signatureBase:
            '"@method": POST\n' +
            '"@authority": auth.acme.test\n' +
            '"@path": /orgs/acme-corp/api/v1/aauth/agent/token\n' +
            '"signature-key": \n' +
            '"content-digest": sha-256=:maoKTEBGVoe/uXlHmt4EeWj7K7xo71Ag/qIPObi3vPw=:\n' +
            '"content-type": application/json\n' +
            '"authorization": \n' +
            '"@signature-params": ("@method" "@authority" "@path" "signature-key" "content-digest" "content-type" "authorization");created=1750000000;nonce="AAECAwQFBgcICQoLDA0ODw"',
    },
};

test('signRequest reproduces the Python SDK signature byte-for-byte', () => {
    const headers = signRequest(PYTHON_VECTOR.privateKeyPem, 'POST', PYTHON_VECTOR.url, {
        body: PYTHON_VECTOR.body,
        agentToken: PYTHON_VECTOR.agentToken,
        created: PYTHON_VECTOR.created,
        nonce: PYTHON_VECTOR.nonce,
    });

    assert.equal(headers['Content-Digest'], PYTHON_VECTOR.expected.contentDigest);
    assert.equal(headers['Content-Type'], 'application/json');
    assert.equal(headers['Signature-Input'], PYTHON_VECTOR.expected.signatureInput);
    assert.equal(headers['Signature'], PYTHON_VECTOR.expected.signature);
    assert.equal(headers['Agent-Auth'], `agent_token=${PYTHON_VECTOR.agentToken}`);
});

test('buildSignatureBase matches the Python/server signature base exactly', () => {
    const components = [
        '@method', '@authority', '@path',
        'signature-key', 'content-digest', 'content-type', 'authorization',
    ];
    const base = buildSignatureBase(
        components,
        {
            '@method': 'POST',
            '@authority': 'auth.acme.test',
            '@path': '/orgs/acme-corp/api/v1/aauth/agent/token',
            'signature-key': '',
            'content-digest': PYTHON_VECTOR.expected.contentDigest,
            'content-type': 'application/json',
            authorization: '',
        },
        PYTHON_VECTOR.created,
        PYTHON_VECTOR.nonce
    );
    assert.equal(base, PYTHON_VECTOR.expected.signatureBase);
});

test('signature verifies against the Ed25519 public key (server-side check)', () => {
    const publicKey = createPublicKey({
        key: { kty: 'OKP', crv: 'Ed25519', x: PYTHON_VECTOR.publicX },
        format: 'jwk',
    });
    // Extract base64url payload from `sig1=:…:`
    const sig = PYTHON_VECTOR.expected.signature.match(/^sig1=:([A-Za-z0-9_-]+):$/)[1];
    assert.equal(verifySignatureBase(PYTHON_VECTOR.expected.signatureBase, sig, publicKey), true);
    // A tampered base must fail
    assert.equal(
        verifySignatureBase(PYTHON_VECTOR.expected.signatureBase.replace('POST', 'GET'), sig, publicKey),
        false
    );
});

test('Content-Digest uses standard base64 (RFC 9530)', () => {
    assert.equal(contentDigestSha256(''), 'sha-256=:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=:');
    assert.equal(contentDigestSha256(PYTHON_VECTOR.body), PYTHON_VECTOR.expected.contentDigest);
});

test('@query is covered if and only if the URL has a query string', () => {
    const withQuery = signRequest(PYTHON_VECTOR.privateKeyPem, 'GET', 'https://api.example.com/v1/data?a=b&c=d', {
        created: PYTHON_VECTOR.created,
        nonce: PYTHON_VECTOR.nonce,
    });
    assert.match(withQuery['Signature-Input'], /"@path" "@query" "signature-key"/);

    const withoutQuery = signRequest(PYTHON_VECTOR.privateKeyPem, 'GET', 'https://api.example.com/v1/data', {
        created: PYTHON_VECTOR.created,
        nonce: PYTHON_VECTOR.nonce,
    });
    assert.doesNotMatch(withoutQuery['Signature-Input'], /@query/);
});

// ─── RFC 7638 thumbprint ──────────────────────────────────────────────

test('jwkThumbprint reproduces the RFC 7638 example vector', () => {
    // The RSA key from RFC 7638 §3.1; expected thumbprint from the RFC.
    const jwk = {
        kty: 'RSA',
        n: '0vx7agoebGcQSuuPiLJXZptN9nndrQmbXEps2aiAFbWhM78LhWx4cbbfAAtVT86zwu1RK7aPFFxuhDR1L6tSoc_BJECPebWKRXjBZCiFV4n3oknjhMstn64tZ_2W-5JsGY4Hc5n9yBXArwl93lqt7_RN5w6Cf0h4QyQ5v-65YGjQR0_FDW2QvzqY368QQMicAtaSqzs8KJZgnYb9c7d0zgdAZHzu6qMQvRL5hajrn1n91CbOpbISD08qNLyrdkt-bFTWhAI4vMQFh6WeZu0fM4lFd2NcRwr3XPksINHaQ-G_xBniIqbw0Ls1jF44-csFCur-kEgU8awapJzKnqDKgw',
        e: 'AQAB',
        alg: 'RS256',
        kid: '2011-04-29',
    };
    assert.equal(jwkThumbprint(jwk), 'NzbLsXh8uDCcd-6MNwXF4W_7noWXFZAfHkxZsRGC9Xs');
});

// ─── Key generation ───────────────────────────────────────────────────

test('generateKeypair produces a usable Ed25519 keypair + JWKS', () => {
    const kp = generateKeypair('my-key');
    assert.match(kp.privateKeyPem, /^-----BEGIN PRIVATE KEY-----/);
    assert.match(kp.publicKeyPem, /^-----BEGIN PUBLIC KEY-----/);
    assert.equal(kp.jwk.kty, 'OKP');
    assert.equal(kp.jwk.crv, 'Ed25519');
    assert.equal(kp.jwk.use, 'sig');
    assert.equal(kp.jwk.kid, 'my-key');
    assert.deepEqual(kp.jwks, { keys: [kp.jwk] });

    // The derived public JWK matches, and signatures roundtrip.
    const derived = publicJwkFromPrivateKey(kp.privateKeyPem);
    assert.equal(derived.x, kp.jwk.x);

    const key = createPrivateKey(kp.privateKeyPem);
    const sig = signSignatureBase('hello world', key);
    const pub = createPublicKey({ key: { kty: 'OKP', crv: 'Ed25519', x: kp.jwk.x }, format: 'jwk' });
    assert.equal(verifySignatureBase('hello world', sig, pub), true);
});

test('RSA keys sign with RSA-PSS-SHA512 (64-byte salt) and self-verify', () => {
    const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });
    const pem = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString();

    const headers = signRequest(pem, 'POST', PYTHON_VECTOR.url, {
        body: PYTHON_VECTOR.body,
        agentToken: 'X',
        created: PYTHON_VECTOR.created,
        nonce: PYTHON_VECTOR.nonce,
    });
    const sig = headers['Signature'].match(/^sig1=:([A-Za-z0-9_-]+):$/)[1];
    // The signature base is identical to the Ed25519 one (same request);
    // only the signature algorithm differs.
    assert.equal(verifySignatureBase(PYTHON_VECTOR.expected.signatureBase, sig, publicKey), true);
});

test('generateNonce yields >= 96 bits of base64url entropy', () => {
    const nonce = generateNonce();
    assert.match(nonce, /^[A-Za-z0-9_-]+$/);
    assert.ok(Buffer.from(nonce, 'base64url').length >= 12);
    assert.notEqual(generateNonce(), nonce);
});
